---
- name: Directorio para backups
  file: path={{ item }} state=directory owner=vagrant group=vagrant
  with_items:
    - /mnt/datos/deploy/backup/redmine/database
    - /mnt/datos/deploy/backup/redmine/code

- name: Crontab backup redmine dabatase
  cron: name="backup redmine dabatase" 
        minute=*/30 
        job="mysqldump --defaults-file=/root/.my.cnf redmine > /mnt/datos/deploy/backup/redmine/database/redmine.dump"

- name: Crontab backup redmine code
  cron: name="backup redmine code" 
        minute=*/30 
        job="tar -c {{ redmine_path }} | gzip --rsyncable > /mnt/datos/deploy/backup/redmine/code/code.tar.gz"
        