---
- name: Package pre-requisites
  apt: name={{ item }} state=latest
  with_items:
    - git
    - imagemagick
    - ruby-openid
    - ruby
    - build-essential
    - ruby-dev
    - libmysqlclient-dev
    - libpq-dev
    - libmagickwand-dev
    - libsqlite3-dev
    
- name: Clone repository
  git: repo=https://github.com/redmine/redmine.git dest="{{ redmine_path }}" version='{{ redmine_version }}' accept_hostkey=yes force=true

- name: Config database
  template: src=database.yml.j2 dest="{{ redmine_path }}/config/database.yml"

- name: Add new Gemfile
  template: src=Gemfile.j2 dest={{ redmine_path }}/Gemfile group=root mode=644

- name: Install Bundler
  shell: "gem install bundler"
  args:
    chdir: "{{ redmine_path }}"

- name: Dependencies installation
  shell: bundle update
  args:
    chdir: "{{ redmine_path }}"  
  
- name: Dependencies installation
  shell: bundle install --without development test
  args:
    chdir: "{{ redmine_path }}"

- name: Session store secret generation
  shell: rake generate_secret_token
  args:
   chdir: "{{ redmine_path }}"
  
- name: Database schema objects creation
  shell: RAILS_ENV=production rake db:migrate
  args:
   chdir: "{{ redmine_path }}"
   
- name: Plugins installation
  shell: RAILS_ENV=production rake redmine:plugins:migrate 
  args:
    chdir: "{{ redmine_path }}"  
     
- name: Database default data set
  shell: RAILS_ENV=production REDMINE_LANG="{{ redmine_lang }}" rake redmine:load_default_data
  args:
   chdir: "{{ redmine_path }}"

- name: Clean up
  shell: bundle exec rake tmp:cache:clear
  args:
    chdir: "{{ redmine_path }}"
  shell: bundle exec rake tmp:sessions:clear
  args:
    chdir: "{{ redmine_path }}"

- include: configure_nginx.yml
- include: configure_thin.yml
- include: configure_backups.yml
