---
- name: Repositorios
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - "deb https://packages.elastic.co/beats/apt stable main"
  
- name: Apt keys
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present

- name: Update apt
  apt: update_cache=yes cache_valid_time=0
  
- name: Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - filebeat
    
- name: Copy filebeat configuration in place.
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0755
  