---
php_version: 7

php7_packages: 
  - php7.1
  - php7.1-common
  - php7.1-cli
  - php7.1-dev
  - php7.1-fpm
  - libpcre3-dev
  - php7.1-gd
  - php7.1-curl
  - php7.1-imap
  - php7.1-json
  - php7.1-opcache
  - php7.1-xml
  - php7.1-mbstring
  - php7.1-mysql
  - php7.1-intl  
  - php-sqlite3
  - php-apcu

php56_packages: 
  - php5.6
  - php5.6-fpm
  - php5.6-mysql
