---
- name: Update apt
  apt: update_cache=yes cache_valid_time=3600

- name: Install System Packages
  apt: pkg={{ item }} state=latest
  with_items: "{{ server.packages }}"

- name: Install Extra Packages
  apt: pkg='{{ item }}' state=latest
  with_items: "{{ server.extra_packages }}"
  when: server.extra_packages is defined

- name: Configure the timezone
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  shell: locale-gen {{server.locale}}

