---
server_repositories: 
    - ppa:ondrej/php    

server_extra_packages: 
    - postfix
    - apache2-utils
  
#server_directories: 
#    - /deploy/backup/website/redis
    
php_version: 71
  
php_socket: unix:/var/run/php/php7.1-fpm.sock
#php_socket: unix:/var/run/php5-fpm.sock

php_webserver_daemon: nginx

php_xdebug_default_enable: 1
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: "false"
php_xdebug_remote_host: 192.168.50.1
php_xdebug_remote_port: "9000"
php_xdebug_remote_log: /tmp/xdebug.log
php_xdebug_remote_autostart: "0"
php_xdebug_max_nesting_level: 256

php_xdebug_idekey: netbeans-xdebug

redis_dbdir: /tmp
redis_databases: 8

nodejs_version: "5.x"
nodejs_npm_global_packages:
  - {name: forever}
  - {name: gulp}

openresty_version: "1.9.7.4"
openresty_modules: 
  - luajit
  - http_dav_module
  - http_flv_module
  - http_geoip_module
  - http_gzip_static_module
  - http_image_filter_module
  - http_realip_module
  - http_stub_status_module
  - http_ssl_module
  - http_sub_module
  - http_xslt_module
  - pcre-jit
  - ipv6
  - http_iconv_module
  - mail
  - mail_ssl_module
  - http_secure_link_module
  - sha1=/usr/include/openssl
  - md5=/usr/include/openssl
  
openresty_sites:   
  - server_name: cms.planb.int
    root: /deploy/projects/planb-cms-project-skeleton/web
    php_socket: "{{ php_socket }}"
    template: symfony
    
  - server_name: showroom.planb.int
    root: /deploy/projects/showroom/dist/   
    source: /deploy/projects/showroom
    port: 3000
    template: node
    
    
varnish_default_vcl_template_path: templates/varnish/default.vcl.j2

mysql_enabled_on_startup: yes

mysql_root_home: /root
mysql_root_username: root
mysql_root_password: root

mysql_databases:
  - name: cms
    encoding: utf8
    collation: utf8_general_ci
   
mysql_users:
  - name: cms
    host: "%"
    password: cms
    priv: "cms.*:ALL"
    
    
mysql_server_id: "1"
mysql_replication_role: 'master'
mysql_replication_master: 'master'

mysql_replication_user:
  name: master
  host: "%"
  password: cms
  priv: "cms.*:ALL"
    
