---
php_socket: unix:/var/run/php/php7.0-fpm.sock
#php_socket: unix:/var/run/php5-fpm.sock

openresty_version: "1.9.7.4"
openresty_modules: 
  - luajit
  - http_dav_module
  - http_flv_module
  - http_geoip_module
  - http_gzip_static_module
  - http_image_filter_module
  - http_realip_module
  - http_stub_status_module
  - http_ssl_module
  - http_sub_module
  - http_xslt_module
  - pcre-jit
  - ipv6
  - http_iconv_module
  - mail
  - mail_ssl_module
  - http_secure_link_module
  - sha1=/usr/include/openssl
  - md5=/usr/include/openssl
  
openresty_sites:   
  - server_name: site1.jump.int
    root: /deploy/projects/site1/web/   
    php_socket: "{{ php_socket }}"
    
  - server_name: site2.jump.int
    root: /deploy/projects/site2/web/   
    php_socket: "{{ php_socket }}"
    
varnish_default_vcl_template_path: templates/varnish/default.vcl.j2


mysql_enabled_on_startup: yes

mysql_root_password: admin

mysql_databases:
  - name: site1
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: site1
    host: "%"
    password: m1sql
    priv: "site1.*:ALL"