---
- hosts: redmine
  vars_files: 
    - ./vars/redmine.yml
  roles:
    - { role: commons }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.nginx }
    - { role: redmine }
    

- hosts: monitoring
  gather_facts: yes
  vars_files: 
    - ./vars/monitoring.yml

  roles:
    - { role: commons }
    - { role: elk }
    
- hosts: web
  roles:
    - { role: commons }
    - { role: filebeat }
