---
- hosts: redmine
  vars_files: 
    - ./vars/redmine.yml
  roles:
    - { role: commons }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.nginx }
    - { role: redmine }
    

- hosts: monitoring
  vars_files: 
    - ./vars/monitoring.yml
  roles:
    - { role: commons }
    - { role: elk }
    
- hosts: website
  vars_files: 
    - ./vars/website.yml
      
  roles:
    - { role: commons }
    - { role: filebeat }
    - { role: geerlingguy.varnish }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.php }
    - { role: geerlingguy.php-xdebug }
    - { role: geerlingguy.composer }
    - { role: openresty }
