---
- hosts: redmine
  vars_files: 
    - ./vars/redmine.yml
  roles:
    - { role: commons }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.nginx }
    - { role: redmine }
    

- hosts: monitoring
  vars_files: 
    - ./vars/monitoring.yml
  roles:
    - { role: commons }
    - { role: elk }
    
- hosts: web
  vars_files: 
    - ./vars/web.yml
  roles:
    - { role: commons }
    - { role: filebeat }
    - { role: openresty }
