#!/usr/bin/env ansible-playbook
# vim:ft=ansible :

---
- hosts: all
  become: true

  vars_files:
    - defaults/main.yml

  tasks:
    - name: include main tasks
      include: tasks/main.yml

    - name: restart php-fpm on ubuntu
      service: name=php7.0-fpm state=restarted
      when: ansible_distribution|lower == "ubuntu"

    - name: restart php-fpm on debian
      service: name=php7.0-fpm state=restarted
      when: ansible_distribution|lower == "debian"

    - name: restart php-fpm on centos
      service: name=php-fpm state=restarted
      when: ansible_distribution|lower == "centos"

    - name: check process
      shell: ps -A | grep php-fpm
      register: php_process

    - name: print process
      debug:
        msg: "{{ php_process.stdout_lines }}"

  handlers:
    - include: handlers/main.yml

